ALTER TABLE Resident
ADD CONSTRAINT res_stdid_fk FOREIGN KEY (Student_ID) REFERENCES Student_Info(Student_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Complaint
ADD CONSTRAINT com_stdid_fk FOREIGN KEY (Student_ID) REFERENCES Resident(Student_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Complaint_Resolution
ADD CONSTRAINT cre_comid_fk FOREIGN KEY (Complaint_ID) REFERENCES Complaint(Complaint_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Events
ADD CONSTRAINT eve_stdid_fk FOREIGN KEY (Student_ID) REFERENCES Resident(Student_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Visitor_Entry
ADD CONSTRAINT vis_stdid_fk FOREIGN KEY (Student_ID) REFERENCES Resident(Student_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Lost_Item
ADD CONSTRAINT los_stdid_fk FOREIGN KEY (Student_ID) REFERENCES Resident(Student_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Room_Allocation
ADD CONSTRAINT ral_stdid_fk FOREIGN KEY (Student_ID) REFERENCES Resident(Student_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Room_Allocation
ADD CONSTRAINT ral_romno_fk FOREIGN KEY (Room_No) REFERENCES Room(Room_No)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Room_Allocation
ADD CONSTRAINT ral_halno_fk FOREIGN KEY (Hall_No) REFERENCES Hall(Hall_No)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Lost_Item
ADD CONSTRAINT los_itmid_fk FOREIGN KEY (Item_ID) REFERENCES Item(Item_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Found_Item
ADD CONSTRAINT fou_losid_fk FOREIGN KEY (Lost_ID) REFERENCES Lost_Item(Lost_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Room
ADD CONSTRAINT roo_halno_fk FOREIGN KEY (Hall_No) REFERENCES Hall(Hall_No)
ON DELETE CASCADE
ON UPDATE CASCADE;