SELECT
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    TABLE_NAME = 'Complaint_Resolution'
    AND TABLE_SCHEMA = 'hall_mgmt';

SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';

SELECT DISTINCT TABLE_SCHEMA
FROM INFORMATION_SCHEMA.TABLES;

SELECT user, host FROM mysql.user;

SELECT * FROM `student_info`;
SELECT * FROM `resident`;
SELECT * FROM `events`;
SELECT * FROM `complaint`;
SELECT * FROM `complaint_resolution`;
SELECT * FROM `visitor_entry`;
SELECT * FROM `room_allocation`;
SELECT * FROM `lost_item`;
SELECT * FROM `found_item`;
SELECT * FROM `room`;
SELECT * FROM `hall`;
SELECT * FROM `item`;