select * from student_info;

select * from room;

SELECT
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    TABLE_NAME = 'Complaint_Resolution'
    AND TABLE_SCHEMA = 'hall_mgmt';

SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';

SELECT DISTINCT TABLE_SCHEMA
FROM INFORMATION_SCHEMA.TABLES;

SELECT user, host FROM mysql.user;
